name: Build and Deploy TypeScript App

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/

  deploy:
    name: Deploy to Netlify
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/

      - name: List Files for Debugging
        run: ls -la build

      - name: Install Netlify CLI
        run: npm install netlify-cli

      - name: Deploy Project to Netlify
        run: |
          echo "Deploying to production. Site ID: ${{ secrets.NETLIFY_SITE_ID }}"
          node_modules/.bin/netlify deploy --dir=build --prod --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }}

  e2e:
    name: Run E2E Tests
    needs: [build, deploy]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run tests
        run: npm run test

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report.html
          path: ./playwright-report/**
          retention-days: 2
